FROM dev

# Your favorite tools
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update \
    && apt-get install --yes \
        ack \
        atop \
        dtrx \
        jq
